apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-vnqzzunr
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-vnqzzunr:772a6d913847bcda8d4e1dd02fce332b03c83fb3@sha256:f0ace71482c736104acfd5f28471fc4db642eaea4c8303d1bf152291bc330be1
          name: container-image
